### ISSUE TITLE
After translate doesn't return to main language

### ISSUE THREAD

**Issue by ghost** [Ultchad/kalliope_neuron_translate#4]
Hi!
After translation using pico2wave (for example to es-ES) that language stay as main language. Can you fix that? After translate should return to english.

**Comment by Ultchad** [comment]
Can you post the synapse ?
And when you say, this language stay as main language, it's for other synapse too ?

**Comment by ghost** [comment]
**Synapse**
  - name: "translate-es"
    signals:
      - order: "translate {{sentence}} to spanish"
      - order: "translate {{sentence}} into spanish"
      - order: "translate {{sentence}} for spanish"
    neurons:
      - translate:
          lang_in: "en"
          lang_out: "es"
          sentence: "{{sentence}}"
          say_template: 
            - "{{ result }}"
          tts:             
            pico2wave:
              language: "es-ES"
              cache: False 

After I use the translator, Spanish becomes the primary language for all synapses that I use later.

**Comment by Ultchad** [comment]
if you use the TTS overwrite on other synapse, Spanish becomes the primary language for all synapses too ? 
Because, the TTS overwrite it implement in core of [kalliope](https://github.com/kalliope-project/kalliope/blob/master/Docs/neurons.md#overridable-parameters) and not in my neuron

PS: can you use the code delimiter 
```markdown
    ```yaml
    YOUR CODE
    ```
```

**Comment by Ultchad** [comment]
No response, too many time
